apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: workstation
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer
